name: epub_view
description: Flutter widget for view EPUB documents on on Web, MacOs, Android and iOS. Based on dart-epub package.
version: 2.2.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/epub_view

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  epubx: 3.0.0-dev.3
  equatable: ^2.0.3
  html: ^0.15.0
  flutter_html: ^2.1.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  rxdart: ^0.27.1
  collection: ^1.15.0
  flutter_bloc: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

